server:
  port: 80
  context-path: /
spring:
  redis:
    host: 120.79.197.130
    port: 6378
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true